#!/bin/sh -e

cmd=$1
shift

if [ "`uname -s`" = "Darwin" ];then
    AM_VERSION=
else
    AM_VERSION=-1.7
fi

case "$cmd" in
  get-version)
        head -1 debian/changelog | sed -e 's/.*(\([^)]*\)).*/\1/'
    ;;
  build-exclude-list|dist-exclude-list|prepare-dist)
    ## These lists can be used to delegate build-time and dist-time exclude lists
    ## For example (syslog-ng-agent):
    ##
    ##    echo "out obj *.aqt *.ncb *.suo *.vcproj.*.user"
    ##
    ;;
  bootstrap)
    set -x
    set -e
    touch README INSTALL
    libtoolize --force --copy --install --verbose
    aclocal${AM_VERSION} -I m4
    gtkdocize --copy
    # wipe out doc generation as it does not work on all platforms
    sed -i -e 's/^install-data-local:/no-\0/' gtk-doc.make
    mkdir -p m4

    autoheader
    automake${AM_VERSION} --add-missing --copy  --force-missing --foreign
    autoconf --force  -i

    ;;
  configure)
    OPTIONS=`getopt -l help,prefix: 'p:' $*`
    if [ $? -ne 0 ]; then
      echo "$0: unknown flags..."
      exit 1
    fi

    eval set -- "$OPTIONS"
    while true ; do
      _arg=$1

      if [ -z "$_arg" ]; then
        break
      fi
      case $1 in
        --prefix|-p)
          shift
          TARGET="$1"
          ;;
      esac
      shift
    done
    if [ "`uname -s`" = "Darwin" ]; then
        OPTS="--disable-static --enable-shared --disable-gtk-doc --with-libiconv=gnu"
        CFLAGS="$CFLAGS -I$TARGET/include"
        export CFLAGS
        CPPFLAGS="$CPPFLAGS -I$TARGET/include"
        export CPPFLAGS

    fi
    echo $LDFLAGS
    ./configure  --prefix "$TARGET" $OPTS $@
    ;;
  make)
    make $@
    ;;
  *)
    echo "Unknown command: $cmd"
    exit 1
    ;;
esac
exit 0
