#!/bin/sh -ex

cmd=$1
shift

case "$cmd" in
  get-version)
        head -1 debian/changelog | sed -e 's/.*(\([^)]*\)).*/\1/'
    ;;
  build-exclude-list|dist-exclude-list|prepare-dist)
    ## These lists can be used to delegate build-time and dist-time exclude lists
    ## For example (syslog-ng-agent):
    ##
    ##    echo "out obj *.aqt *.ncb *.suo *.vcproj.*.user"
    ##
    ;;
  bootstrap)
    set -e
    touch README INSTALL
    mkdir -p m4
    libtoolize --force --copy --install --verbose
    aclocal${AM_VERSION} -I m4
    gtkdocize --copy || true
    # wipe out doc generation as it does not work on all platforms
    sed -i -e 's/^install-data-local:/no-\0/' gtk-doc.make || true

    autoheader
    automake${AM_VERSION} --add-missing --copy  --force-missing --foreign
    autoconf --force  -i

    find -name libtool -o -name ltmain.sh | xargs sed -i -e "s,'file format pe-i386.*\?','file format \(pei\*-i386\(\.\*architecture: i386\)\?|pe-arm-wince|pe-x86-64\)'," -e 's,cmd \/\/c,,'
    ;;
  configure)
    OPTIONS=`getopt -l help,prefix: 'p:' $*`
    if [ $? -ne 0 ]; then
      echo "$0: unknown flags..."
      exit 1
    fi

    eval set -- "$OPTIONS"
    while true ; do
      _arg=$1

      if [ -z "$_arg" ]; then
        break
      fi
      case $1 in
        --prefix|-p)
          shift
          TARGET="$1"
          ;;
        --)
          shift
          break
          ;;
      esac
      shift
    done
    if [ "$ZBS_BUILDER_TYPE" = "mingw" ]; then
        OPTS="--disable-static --enable-shared --disable-gtk-doc --with-libiconv=gnu"
        CFLAGS="$CFLAGS -I$TARGET/include"
        export CFLAGS
        CPPFLAGS="$CPPFLAGS -I$TARGET/include"
        export CPPFLAGS
    fi
    CFLAGS="$CFLAGS -g"
    ./configure  --prefix "$TARGET" $OPTS $@
    ;;
  make)
    export PATH="$PWD/glib/.libs:$PWD/gobject/.libs:$PWD/gmodule/.libs:$PWD/gthread/.libs:$PATH"
    case $1 in
      check)
        if [ "$ZBS_BUILDER_TYPE" = "mingw" ]; then
          cd tests
          make module-test.exe
          ./module-test.exe
        else
          make $@
        fi
        ;;
      *) make $@;;
    esac
    ;;
  *)
    echo "Unknown command: $cmd"
    exit 1
    ;;
esac
exit 0
