name: glib
builder:
  name: AutotoolsBuilder
  flags: "make-dist-need-make"
  configure_options: --disable-static --enable-shared --disable-gtk-doc --with-libiconv=gnu
platforms:
  - aix-6.1/powerpc
  - windows-2012/amd64
  - windows-2012/i386
  - linux-glibc2.11/amd64
